<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyBlazorLib\MyBlazorLib.csproj" />
    <ProjectReference Include="..\SharedModelsLib\SharedModelsLib.csproj" />
  </ItemGroup>

</Project>
